<div class="h-screen w-screen bg-gray-200 flex justify-center items-center">
    <form action="#" method="post" class="text-slate-700 bg-white p-3 rounded-lg shadow-sm w-3/4">
        <div class="flex">
            <div class="w-full mx-1">
                <label for="name" class="">
                    <p class="text-md p-1">Default Price</p>
                    <input type="text" name="dprice" placeholder="Default Price" class="w-full rounded-lg border border-slate-300 shadow" id="">
                </label>
            </div>
            <div class="w-full mx-1">
                <label for="name" class="">
                    <!-- <span class="bg-indigo-500 p-1 rounded-full mr-1 text-gray-100 text-xs">trending</span> -->
                    <p class="text-md p-1">Default Stock</p>
                    <input type="text" name="dstock" placeholder="Default Stock" class="placeholder:italic w-full rounded-lg border border-slate-300 shadow" id="">
                </label>
            </div>
        </div>
        <div class="flex">
            <div class="w-full mx-1">
                <label for="name" class="">
                    <p class="text-md p-1">Default Zipcode</p>
                    <input type="text" name="dzipcode" placeholder="Default Zipcode" class="w-full rounded-lg border border-slate-300 shadow" id="">
                </label>
            </div>
            <div class="w-full mx-1">
                <label for="name" class="">
                    <!-- <span class="bg-indigo-500 p-1 rounded-full mr-1 text-gray-100 text-xs">trending</span> -->
                    <p class="text-md p-1">Title optimization</p>
                    <select name="titleopti" id="" class="w-full rounded-lg border border-slate-300 shadow">
                        <option value="tags">With Tags</option>
                        <option value="notags">Without Tags</option>
                    </select>
                    <!-- <input type="text" name="stock" placeholder="stock" class="w-full rounded-lg border border-slate-300 shadow" id=""> -->
                </label>
            </div>
        </div>
        <div class="flex px-3 pt-3">
            <button class="w-full p-2 text-gray-100 rounded-lg bg-indigo-500"><i class="fa fa-save text-sm"></i> Save Settings</button>
        </div>
    </form>
</div>