<div class="h-screen w-screen bg-gray-200 flex justify-center items-center">
    <form action="#" method="post" class="text-slate-700 bg-white p-3 rounded-lg shadow-sm w-3/4">
        <div class="flex">
            <div class="w-full mx-1">
                <label for="name" class="">
                    <p class="text-md p-1">Customer Name</p>
                    <input type="text" name="name" placeholder="Customer Name" class="w-full rounded-lg border border-slate-300 shadow" id="" required>
                </label>
            </div>
            <div class="w-full mx-1">
                <label for="name" class="">
                    <!-- <span class="bg-indigo-500 p-1 rounded-full mr-1 text-gray-100 text-xs">trending</span> -->
                    <p class="text-md p-1">Zipcode</p>
                    <input type="text" name="zipcode" placeholder="Zipcode" class="placeholder:italic w-full rounded-lg border border-slate-300 shadow" id="">
                </label>
            </div>
        </div>
        <div class="flex mt-1">
            <div class="w-full mx-1">
                <label for="name" class="">
                    <p class="text-md p-1">Customer Address</p>
                    <textarea type="text" name="description" placeholder="Customer Address" class="w-full rounded-lg border border-slate-300 shadow"></textarea>
                </label>
            </div>
        </div>
        <div class="flex">
            <div class="w-full mx-1">
                <label for="name" class="">
                    <p class="text-md p-1">Product</p>
                    <select name="product" id="" class="w-full rounded-lg border border-slate-300 shadow">
                        <option value="1">Product 1</option>
                        <option value="1">Product 1</option>
                        <option value="1">Product 1</option>
                        <option value="1">Product 1</option>
                        <option value="1">Product 1</option>
                    </select>
                    <!-- <input type="text" name="price" placeholder="price" class="w-full rounded-lg border border-slate-300 shadow" id=""> -->
                </label>
            </div>
            <div class="w-full mx-1">
                <label for="name" class="">
                    <!-- <span class="bg-indigo-500 p-1 rounded-full mr-1 text-gray-100 text-xs">trending</span> -->
                    <p class="text-md p-1">Quantity</p>
                    <input type="text" name="quantity" placeholder="Quantity" class="w-full rounded-lg border border-slate-300 shadow" id="">
                </label>
            </div>
        </div>
        <div class="flex px-3 pt-3">
            <button class="w-full p-2 text-gray-100 rounded-lg bg-indigo-500"><i class="fa fa-box text-sm"></i> Make Order</button>
        </div>
    </form>
</div>